In [3]:
import numpy as np
import pandas as pd
import json
from google import genai

from google.oauth2.service_account import Credentials
from google.cloud import storage
import os

scopes = ["https://www.googleapis.com/auth/cloud-platform"]

SERVICE_ACCOUNT_FILE = "/Data2/Arun-UAV/NLP/account_3.json"
credentials = Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=scopes)

client = storage.Client(credentials=credentials)

gen_client = genai.Client(
    vertexai=True,
    project='clean-silo-477405-i6',   # or set directly
    location='global',    # or set directly, e.g. "us-central1"
    credentials=credentials
)

In [45]:
final_df = pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/our_proposed_dataset_2/gcp_upload_urs.csv")
prompt_df = pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/our_proposed_dataset_2/all_models_generated/combined_qa_dataset_5k.csv")

In [46]:
final_df.head(2)

,local_path,gcs_uri,error
0,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,gs://train_data_vision_3/VG_target_20k/0000000...,NaN
1,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,gs://train_data_vision_3/VG_target_20k/0000000...,NaN

In [47]:
final_df.shape

(500, 3)

In [48]:
prompt_df.head(2)

,image_id,image_path,objects,question,answer,data_type,question_id
0,632,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,"[{""category_id"": 65, ""category_name"": ""bed"", ""...",What do you see in this image?,"A cozy bedroom with a blue comforter bed, wood...",caption_nonhalu_qwen,0
1,776,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,"[{""category_id"": 88, ""category_name"": ""teddy b...",Describe what’s happening in this picture.,Three teddy bears are cuddling together in a c...,caption_nonhalu_qwen,1

In [49]:
prompt_df.shape

(4930, 7)

# batch creation

In [1]:
# from tqdm import tqdm

# def get_prompt(objects, image_id):
#     prompt = f"""
# Generate two distinct types of questions for the given image:

# 1. Visual QA.

# 2. Instruction-Following.

# Design each question to appear natural and realistic, yet likely to induce hallucinations like object existence, relations, different attributes not colours, scene, actions etc..

# Rules:
# - if you are inverting new objects for hallucination you are free to use but make sure they are somewhat relevant to image context.

# - if you are creating other types of hallucinations like relation, attributes, counts, scene, actions etc. make sure they are use this objects that are present in the image
# Objects in image: {objects} (Please dont use other objects other than provided for this category)



# ###sample qas Note (below are just exaples they do not produced for hallucination context but to give idea about categories of questions to be generated):

# ### 🧠 General Object-Level

# 1. What animal is in the picture?
# 2. What color is the car?
# 3. How many chairs are visible?
# 4. What is the person holding?
# 5. Is there any fruit on the table?

# ---

# ### 🎨 Attributes & Appearance

# 6. What pattern is on the shirt?
# 7. Is the sky cloudy or clear?
# 8. What color are the flowers?
# 9. Are the shoes clean or dirty?
# 10. Is the light on or off?

# ---

# ### 🔄 Relations & Spatial Reasoning

# 11. What is next to the bicycle?
# 12. Is the dog in front of or behind the boy?
# 13. What is under the table?
# 14. Is the man standing beside a car?
# 15. What is on top of the shelf?

# ---

# ### 🧍‍♂️ Actions & Events

# 16. What is the person doing?
# 17. Is someone cooking food?
# 18. Are they playing a sport?
# 19. What activity is taking place?
# 20. Is anyone using a phone?

# ----

# ### 🌆 Scene & Context

# 26. Is this indoors or outdoors?
# 27. What place is this photo taken in?
# 28. Is this a kitchen or a bedroom?
# 29. What time of day does it seem to be?
# 30. Is it raining or sunny?

# ---

# Would you like me to extend this to **100 or 500 questions** and export as a **Python list** (for dataset generation or prompting)?
# image_id : {image_id}

# Output format:

# {{
# "visual_qa": "<question>",
# "instruction_following": "<instruction>",
# }}
# """
#     return prompt
  
# all_res = []
# for inx, row in tqdm(prompt_df.iterrows()):
#     objects = set([i["category_name"] for i in eval(row["objects"])])
#     PROMPT = get_prompt(objects, image_id=row["image_id"])   

#     img_path = row["image_path"]
#     uri = final_df[final_df["local_path"] == img_path]["gcs_uri"].iloc[0]
#     res = {"request":{"contents": [{"role": "user", "parts": [{"text": PROMPT}, {"fileData": {"fileUri": uri, "mimeType": "image/jpeg"}}]}], 
#                       "generationConfig": {"temperature": 0, "topP": 1, "maxOutputTokens": 2500,"thinking_config":{"thinking_budget":1000}}}}
#     all_res.append(res)

In [69]:

# PROMPT = """
# You are a specialist in rich and precise scene understanding.
# Given an input image, generate a comprehensive, contextually aware, and fluent description that captures all key visual elements, their relationships, emotions, and possible context or story.

# Your description should go beyond short captions — it must resemble a paragraph of visual storytelling that includes:

# Scene type: indoor/outdoor, environment, lighting, time of day
# Objects and entities: names, counts, shapes, colors, materials
# Actions and interactions: what the people or objects are doing
# Spatial layout: foreground, background, relative positions
# Emotions or atmosphere: tone, mood, aesthetics
# Possible context: what might be happening or implied by the scene

# Avoid generic or repetitive statements. Be vivid, factual, and coherent. Use natural language instead of bullet points.

# Output JSON format:
# {image_description: <full attached image description>}
# """

# all_res = []
# for uri in df["gcs_uri"].tolist():
#     res = {"request":{"contents": [{"role": "user", "parts": [{"text": PROMPT}, {"fileData": {"fileUri": uri, "mimeType": "image/jpeg"}}]}], 
#                       "generationConfig": {"temperature": 0.6, "topP": 1, "maxOutputTokens": 1000,"thinking_config":{"thinking_budget":0}}}}
#     all_res.append(res)

In [ ]:
# def get_prompt(question, ans, _id):
#   prompt = f"""
# You are given an **image** and ** question and answer** related to that image.
# Your job is to analyze each q and a separately and return **two lists of single words (no phrases)**:

# 1. **`hallucination_candidates`** — all meaningful words that are semantically important for hallucination detection, belonging to categories like:

#    * **objects** (car, tree, person, lamp),
#    * **attributes** (red, shiny, tall),
#    * **relations** (on, under, behind, next_to),
#    * **actions** (running, holding, sitting),
#    * **count** (two, many, three),
#    * **scene/context** (beach, kitchen, street).
#    * **Decision tokens** yes, no, true, false, present, absent, exist, not, visible, correct

#    Include only **specific, content-bearing words** that could be visually verifiable or falsifiable from the image.
#    Do **not** include stopwords, determiners, or abstract terms.

# 2. **`hallucinated_words`** — a subset of the above list that are **not visually supported** or are **contradicted** by the image content (i.e., hallucinated terms).

# **Inputs:**

# <attached image> {_id}

# Question: {question}
# Answer: {ans}

# **Output format (strict JSON per caption pair):**

# ```json
# {{
#     "hallucination_candidates": ["word1", "word2", ...],
#     "hallucinated_words": ["wordX", "wordY", ...]
#   }}
# ```
# Note: extract "hallucination_candidates" and "hallucinated_words" from the Answer strictly not from the Question

# Ensure both lists contain **only lowercase single words** and are **deduplicated**.
# Focus on **important, visually grounded words** — not all tokens.

# ---
# """
#   return prompt

# all_res = []
# for inx, row in prompt_df.iterrows():
#     question = row["prompt"].replace("<image>", "")
#     nh_ans  = row["source_text"]
#     h_ans = row["hallucinated_text"]
#     PROMPT = get_prompt(question, nh_ans, h_ans)
#     img_path = f"/Data2/Arun-UAV/NLP/vision_halu/visual_genome/target_images/{row['image_id']}.jpg"
#     uri = df[df["local_path"] == img_path]["gcs_uri"].iloc[0]

#     res = {"request":{"contents": [{"role": "user", "parts": [{"text": PROMPT}, {"fileData": {"fileUri": uri, "mimeType": "image/jpeg"}}]}], 
#                       "generationConfig": {"temperature": 0, "topP": 1, "maxOutputTokens": 2000,"thinking_config":{"thinking_budget":1000}}}}
#     all_res.append(res)

In [53]:
from tqdm import tqdm

def get_prompt(qus, ans, _id):
  prompt = f"""
You are given an **image** and **question–answer (QA) pair** about that image.

Your task is to carefully analyze **each QA pair independently** and return results **in the same order** as the input QA pairs.  
For each QA pair, produce **two disjoint lists of single words (no phrases)**:

1. **`hallucination_candidates`** — words that are **not visually supported or contradicted** by the image (hallucinated).
2. **`non_hallucination_candidates`** — words that are **visually grounded and supported** by the image.

Both lists must be **mutually exclusive** (no word appears in both) and contain **only lowercase, deduplicated single words**.

Each list should include only **meaningful, visually verifiable words** from the answer (not from the question), belonging to categories like:
- **objects:** car, tree, person  
- **attributes:** red, shiny, tall  
- **relations:** on, under, behind, next_to  
- **actions:** running, holding, sitting  
- **count:** two, three, many  
- **scene/context:** beach, kitchen, street  
- **decision tokens:** yes, no, true, false, present, absent, exist, not, visible, correct  

**Important note on decision tokens:**  
Be very careful with labeling decision tokens (e.g., "yes", "no"). Always indicate **what they correspond to** — e.g., *“yes (object present)”*, *“no (attribute absent)”* — and include them in the correct list according to the image evidence.

**Inputs:**

<attached image> {_id}

qa_pairs:
Question: {qus}
Answer: {ans}

**Output format (strict JSON list, one object per QA pair, same order):**

```json
[
  {{
    "hallucination_candidates": ["word1", "word2", ...],
    "non_hallucination_candidates": ["word3", "word4", ...]
  }},
  ... 
]
```
Only extract from the Answer text, not the Question.
Focus on visually meaningful content words, and ensure no overlap between the two lists.

very very important note:  Please only extract target words type give such as  objects, attributes, relations, actions, count, scene/context, decision tokens, please dont dont iclude any oather types of words
"""
  return prompt
  
all_res = []
for inx, row in tqdm(prompt_df.iterrows()):
    question = row["question"]
    ans  = row["answer"]
    PROMPT = get_prompt(question, ans, row["question_id"])
    img_path = row["image_path"]
    uri = final_df[final_df["local_path"] == img_path]["gcs_uri"].iloc[0]
    res = {"request":{"contents": [{"role": "user", "parts": [{"text": PROMPT}, {"fileData": {"fileUri": uri, "mimeType": "image/jpeg"}}]}], 
                      "generationConfig": {"temperature": 0, "topP": 1, "maxOutputTokens": 2500,"thinking_config":{"thinking_budget":1000}}}}
    all_res.append(res)

4930it [00:01, 3353.81it/s]

In [55]:
# print(PROMPT)

In [56]:
df = pd.DataFrame(all_res)
df.to_json("/Data2/Arun-UAV/NLP/vision_halu/train_datasets/gemini_batch.jsonl", orient="records", lines=True)

# Uploading files to gcp

In [57]:
def upload_to_gcs(local_path: str, gcs_uri: str):
    """
    Upload a local file to a target GCS URI.

    Args:
        local_path (str): Local file path to upload.
        gcs_uri (str): Target GCS URI like 'gs://my-bucket/path/to/upload.txt'
        service_account_path (str): Path to GCP service account JSON.
    """
    if not gcs_uri.startswith("gs://"):
        raise ValueError("Invalid GCS URI. Must start with gs://")

    parts = gcs_uri[5:].split("/", 1)
    bucket_name = parts[0]
    blob_name = parts[1]

    bucket = client.bucket(bucket_name)
    blob = bucket.blob(blob_name)

    blob.upload_from_filename(local_path)

    print(f"✅ Uploaded {local_path} → {gcs_uri}")

In [58]:
upload_to_gcs(local_path="/Data2/Arun-UAV/NLP/vision_halu/train_datasets/gemini_batch.jsonl", gcs_uri = "gs://train_data_vision_3/gemini_batch_info/gemini_batch.jsonl")

✅ Uploaded /Data2/Arun-UAV/NLP/vision_halu/train_datasets/gemini_batch.jsonl → gs://train_data_vision_3/gemini_batch_info/gemini_batch.jsonl

In [59]:
# start batch processing

# start batch processing

In [60]:
import time

from google import genai
from google.genai.types import CreateBatchJobConfig, JobState, HttpOptions
output_uri = "gs://train_data_vision_3/gemini_batch_info/"

# See the documentation: https://googleapis.github.io/python-genai/genai.html#genai.batches.Batches.create
job = gen_client.batches.create(
    model="gemini-2.5-flash",
    src="gs://train_data_vision_3/gemini_batch_info/gemini_batch.jsonl",
    config=CreateBatchJobConfig(dest=output_uri),
)
print(f"Job name: {job.name}")
print(f"Job state: {job.state}")

Job name: projects/370890740177/locations/global/batchPredictionJobs/8248712153435996160
Job state: JOB_STATE_PENDING

In [62]:
job_info = gen_client.batches.get(name=job.name)
job_info.state

# download batch results

In [63]:
def download_from_gcs(gcs_uri: str, local_path: str):
    """
    Download a file from GCS based on its gs:// URI.

    Args:
        gcs_uri (str): GCS URI like 'gs://my-bucket/path/to/file.txt'
        local_path (str): Path to store the downloaded file locally.
    """
    # Parse bucket and blob name
    if not gcs_uri.startswith("gs://"):
        raise ValueError("Invalid GCS URI. Must start with gs://")

    parts = gcs_uri[5:].split("/", 1)
    bucket_name = parts[0]
    blob_name = parts[1]
    
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(blob_name)

    os.makedirs(os.path.dirname(local_path), exist_ok=True)
    blob.download_to_filename(local_path)

    print(f"✅ Downloaded {gcs_uri} → {local_path}")

In [64]:
download_from_gcs(gcs_uri="gs://train_data_vision_3/gemini_batch_info/prediction-model-2025-11-07T21:00:58.650925Z/predictions.jsonl", local_path ="/Data2/Arun-UAV/NLP/vision_halu/train_datasets/gemini_btach_res.jsonl")

✅ Downloaded gs://train_data_vision_3/gemini_batch_info/prediction-model-2025-11-07T21:00:58.650925Z/predictions.jsonl → /Data2/Arun-UAV/NLP/vision_halu/train_datasets/gemini_btach_res.jsonl

In [65]:
pred_data = pd.read_json("/Data2/Arun-UAV/NLP/vision_halu/train_datasets/gemini_btach_res.jsonl", lines=True)

In [66]:
# def get_word_2_bbox(target_df, objects_df):
#     bbox_map = {}
#     for row in target_df.iterrows():
#         word = row[1]["word"]
#         obj_ids = row[1]["objects_involved"]
#         bbox = objects_df[objects_df["id"].isin(obj_ids)]["bounding_box"].to_list()
#         bbox_map[word] = bbox
#     return bbox_map

In [ ]:
# question_id

'7288427d-53ec-4ab8-9a87-76184c0987af'

In [44]:
res.keys()

dict_keys(['hallucination_candidates', 'non_hallucination_candidates'])

In [91]:
from tqdm import tqdm

all_res  = []
error = 0
for inx, row in tqdm(pred_data.iterrows()):
    try:
        res = eval(row["response"]["candidates"][0]["content"]["parts"][0]["text"].replace("json", "").strip("```"))[0]
        img_name = row["request"]["contents"][0]["parts"][1]["fileData"]["fileUri"].split("/")[-1]
        question_id = int(row["request"]["contents"][0]["parts"][0]["text"].split("<attached image> ")[-1].split("qa_pairs:")[0].strip("\n").strip(""))
        
        req_info = prompt_df[prompt_df["question_id"] == question_id]
        
        question = req_info["question"].iloc[0]
        ans = req_info["answer"].iloc[0]
        image_id = req_info["image_id"].iloc[0]
        image_path  = req_info["image_path"].iloc[0]
        objects = req_info["objects"].iloc[0]
        
        halu = res["hallucination_candidates"]
        non_halu = res["non_hallucination_candidates"]

        all_res.append({"image_id": img_name, "question_id": question_id, "image_path": image_path, "question": question, "answer": ans, 
                        "hallucination": halu, "non_hallucination": non_halu, "objects": objects})
    except Exception as e:
        print(e)
        error += 1

2579it [00:01, 2348.64it/s]

invalid syntax. Perhaps you forgot a comma? (<string>, line 9)

4928it [00:02, 2327.08it/s]

invalid syntax. Perhaps you forgot a comma? (<string>, line 8)

4930it [00:02, 2319.02it/s]

In [102]:
result_df = pd.DataFrame(all_res)

In [103]:
result_df

,image_id,question_id,image_path,question,answer,hallucination,non_hallucination,objects
0,000000109976.jpg,1578,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,How would you interpret this image?,The image depicts a clean and well-organized k...,"[toaster, two, ovens, left, right, side, bottl...","[kitchen, clean, well-organized, white, applia...","[{""category_id"": 44, ""category_name"": ""bottle""..."
1,000000334555.jpg,2250,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,Describe the pattern on the cow.,The cow has a black and white pattern on its b...,[],"[cow, black, white, pattern, body]","[{""category_id"": 3, ""category_name"": ""car"", ""b..."
2,000000407646.jpg,4293,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,Describe the scene as if the tennis player jus...,"The tennis player, dressed in a vibrant green ...","[vibrant, poised, triumphant, grin, powerful, ...","[tennis, player, green, shirt, black, shorts, ...","[{""category_id"": 1, ""category_name"": ""person"",..."
3,000000286907.jpg,246,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,What do you observe in the background and fore...,"In the foreground, there’s a blue toilet with ...","[cleaning, warning]","[blue, toilet, lid, up, small, trash, can, cru...","[{""category_id"": 70, ""category_name"": ""toilet""..."
4,000000513041.jpg,1915,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,What is the image showing us?,The image shows a table with a pizza on a plat...,"[social, gathering, meal, shared, friends, fam...","[table, pizza, plate, person, pointing, wine, ...","[{""category_id"": 67, ""category_name"": ""dining ..."
...,...,...,...,...,...,...,...,...
4923,000000519569.jpg,4877,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,What is the color of the clock above the oven?,The color of the clock above the oven is black.,"[clock, above, black]",[oven],"[{""category_id"": 44, ""category_name"": ""bottle""..."
4924,000000292155.jpg,2222,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,Count how many different colored stripes are o...,The umbrella has six different colored stripes.,[six],"[umbrella, different, colored, stripes]","[{""category_id"": 28, ""category_name"": ""umbrell..."
4925,000000003553.jpg,991,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,Describe the relationship between the position...,"In the image, there is a person standing on a ...","[another, second, placed, likely, belonging, s...","[image, person, standing, on, skateboard, visi...","[{""category_id"": 1, ""category_name"": ""person"",..."
4926,000000247917.jpg,4164,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,Identify the person who is currently throwing ...,None of the individuals in the image are activ...,"[throwing, baseball, motion]","[none, individuals, image, actively, group, po...","[{""category_id"": 1, ""category_name"": ""person"",..."
4927,000000581482.jpg,984,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,Are there any travelers checking the time on t...,"No, the image shows the clock in a grand, empt...",[travelers],"[no, clock, grand, empty, station, hall, visible]","[{""category_id"": 85, ""category_name"": ""clock"",..."

In [104]:
result_df.index

RangeIndex(start=0, stop=4928, step=1)

In [108]:
result_df.head(2)

,image_id,question_id,image_path,question,answer,hallucination_candidates,candidates,objects
0,000000109976.jpg,1578,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,How would you interpret this image?,The image depicts a clean and well-organized k...,"[toaster, two, ovens, left, right, side, bottl...","[kitchen, clean, well-organized, white, applia...","[{""category_id"": 44, ""category_name"": ""bottle""..."
1,000000334555.jpg,2250,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,Describe the pattern on the cow.,The cow has a black and white pattern on its b...,[],"[cow, black, white, pattern, body]","[{""category_id"": 3, ""category_name"": ""car"", ""b..."

In [106]:
result_df = result_df.rename(columns={"non_hallucination": "candidates", "hallucination": "hallucination_candidates"})

In [109]:
result_df.shape

(4928, 8)

In [110]:
result_df.head(2)

,image_id,question_id,image_path,question,answer,hallucination_candidates,candidates,objects
0,000000109976.jpg,1578,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,How would you interpret this image?,The image depicts a clean and well-organized k...,"[toaster, two, ovens, left, right, side, bottl...","[kitchen, clean, well-organized, white, applia...","[{""category_id"": 44, ""category_name"": ""bottle""..."
1,000000334555.jpg,2250,/Data2/Arun-UAV/NLP/vision_halu/our_proposed_d...,Describe the pattern on the cow.,The cow has a black and white pattern on its b...,[],"[cow, black, white, pattern, body]","[{""category_id"": 3, ""category_name"": ""car"", ""b..."

In [111]:
result_df.to_csv("/Data2/Arun-UAV/NLP/vision_halu/benchmarks/ours/gemini_labled_ours_5k.csv", index=False)

In [222]:
target_data = target_data[((target_data["hallucination_candidates"].apply(lambda x: len(x) != 0 )) | (target_data["candidates"].apply(lambda x: len(x) !=0)))]

In [223]:
target_data.shape

(19991, 8)

In [227]:
target_data_s = target_data[target_data["answer"].apply(lambda x: len(x.split(" ")) <= 6 and x[0].isalpha())]
target_data_l = target_data[target_data["answer"].apply(lambda x: len(x.split(" ")) > 6 and x[0].isalpha())]

In [228]:
target_data_s.shape

(11970, 8)

In [229]:
target_data_l.shape

(7702, 8)

In [233]:
target_data_s.head(2)

,question,answer,hallucination_candidates,candidates,image_id,question_id,image_path,data_type
8,What color is the broccoli?,Green.,[],[green],2335559,18331,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,vga
9,What color is the broccoli?,The broccoli is green.,[],"[broccoli, green]",2335559,18331,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,vga

In [234]:
target_data_l.head(2)

,question,answer,hallucination_candidates,candidates,image_id,question_id,image_path,data_type
11,What color is the bottom of the wall?,The bottom of the wall is yellow.,[],"[bottom, wall, yellow]",2350910,20524,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,vga
13,How was the broccoli prepared?,The broccoli was prepared by being steamed.,[steamed],"[broccoli, prepared]",2374337,21835,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,vga

In [232]:
target_data_s.to_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/vga/small_vga_gemini_labeled.csv")
target_data_l.to_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/vga/large_vga_gemini_labeled.csv")

In [95]:
df_2.shape

(18806, 8)

In [126]:
gqa_data.to_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/vga/total_vga_gemini_labeled.csv", index=False)

In [ ]:
visual_genome_small

In [78]:
total_res_df.to_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/vga_gqa_gemini_labeled_res.csv", index=False)

In [ ]:
# pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/holoc/gemini_labled_total_holoc_data.csv")

,question,answer,hallucination_candidates,candidates,image_id,question_id,image_path,data_type
0,What's happening in the scene?,In this picture there is a lady on the right s...,"['lady', 'right']","['operating', 'phone', 'train', 'side', 'lamps...",2380299.jpg,5413,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,caption
1,Can you describe the main features of this ima...,"In this image, there are some objects in the r...","['iron', 'elephant']","['objects', 'racks', 'washbasin', 'tap', 'rod'...",2388073.jpg,6374,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,caption
2,Write a detailed description of the given image.,"In this image, there are some objects in the r...","['iron', 'elephant', 'tan']","['objects', 'racks', 'washbasin', 'tap', 'rod'...",2388073.jpg,6374,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,caption
3,What do you see happening in this image?,Food is presented on a table in a lovely way. ...,"['lovely', 'peppers', 'tofu', 'meat']","['food', 'presented', 'table', 'brown', 'bowl'...",2396708.jpg,7332,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,caption
4,What do you see happening in this image?,Food is presented on a table in a lovely way. ...,"['lovely', 'peppers', 'tofu', 'meat', 'glass',...","['food', 'presented', 'table', 'brown', 'bowl'...",2396708.jpg,7332,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,caption
...,...,...,...,...,...,...,...,...
87537,Q: What is the color of the umbrella? A:,brown,['brown'],[],2320624.jpg,29621,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,vqa
87538,The coach is wearing what?,pants,[],['pants'],2363810.jpg,30561,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,vqa
87539,The coach is wearing what?,hat,[],['hat'],2363810.jpg,30561,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,vqa
87540,"Based on the image, respond to this question w...",brown,[],['brown'],2398141.jpg,35476,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,vqa
87541,"Based on the image, respond to this question w...",white,['white'],[],2398141.jpg,35476,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,vqa

In [129]:
final_res_df = pd.merge(clean_res_df, prompt_df, on = "image_id", how='left')

In [128]:
clean_res_df.head(2)

,image_id,word_2_bbox
0,COCO_train2014_000000507721.jpg,"{'grass': [0, 400, 1000, 1000], 'structure': [..."
1,COCO_train2014_000000560217.jpg,"{'cat': [150, 180, 850, 800], 'film stock labe..."

In [122]:
prompt_df.head(2)

,image_id,answer,question,question_id,image_path
8803,COCO_train2014_000000559900.jpg,This indoor scene captures two young boys enjo...,Please describe this image in detail.,8803,/Data2/Arun-UAV/NLP/vision_halu/train_datasets...
8660,COCO_train2014_000000463308.jpg,This outdoor scene captures a dynamic moment d...,Please describe this image in detail.,8660,/Data2/Arun-UAV/NLP/vision_halu/train_datasets...

In [136]:
final_res_df.head(2)

,image_id,word_2_bbox,answer,question,question_id,image_path
0,COCO_train2014_000000507721.jpg,"{'grass': [0, 400, 1000, 1000], 'structure': [...","This outdoor scene captures a rustic, rural la...",Please describe this image in detail.,5616,/Data2/Arun-UAV/NLP/vision_halu/train_datasets...
1,COCO_train2014_000000560217.jpg,"{'cat': [150, 180, 850, 800], 'film stock labe...","This outdoor, dimly lit scene, captured likely...",Please describe this image in detail.,1966,/Data2/Arun-UAV/NLP/vision_halu/train_datasets...

In [145]:
final_res_df = pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/evidence_head_train_datasets/coco_long_captions/coco_img_des_10k_bb_annot.csv")

In [146]:
final_res_df.head(2)

,image_id,word_2_bbox,answer,question,question_id,image_path
0,COCO_train2014_000000507721.jpg,"{'grass': [0, 400, 1000, 1000], 'structure': [...","This outdoor scene captures a rustic, rural la...",Please describe this image in detail.,5616,/Data2/Arun-UAV/NLP/vision_halu/train_datasets...
1,COCO_train2014_000000560217.jpg,"{'cat': [150, 180, 850, 800], 'film stock labe...","This outdoor, dimly lit scene, captured likely...",Please describe this image in detail.,1966,/Data2/Arun-UAV/NLP/vision_halu/train_datasets...

In [47]:
import re
import json

def extract_qa_pairs(text: str):
    """
    Extracts qa_pair_1 and qa_pair_2 (Question and Answer) from multiple prompts
    having the same structure.

    Args:
        text (str): Input text containing multiple prompt blocks.

    Returns:
        list[dict]: List of dictionaries, each containing qa_pair_1 and qa_pair_2 with Q/A.
    """
    # Pattern to match both caption_pair_1 and caption_pair_2 blocks
    pattern = re.compile(
        r'caption_pair_1:\s*Question:\s*(?P<q1>.*?)\s*Caption:\s*(?P<a1>.*?)\s*'
        r'caption_pair_2:\s*Question:\s*(?P<q2>.*?)\s*Caption:\s*(?P<a2>.*?)(?=\n\s*\n|$)',
        re.DOTALL | re.IGNORECASE
    )

    results = []
    for match in pattern.finditer(text):
        qa_dict = {
            "caption_pair_1": {
                "Question": match.group("q1").strip(),
                "Caption": match.group("a1").strip()
            },
            "caption_pair_2": {
                "Question": match.group("q2").strip(),
                "Caption": match.group("a2").strip()
            }
        }
        results.append(qa_dict)

    return results

In [109]:
all_res = []
error = 0
for inx, row in pred_data.iterrows():
    try:
        img_name = row["request"]["contents"][0]["parts"][1]["fileData"]["fileUri"].split("/")[-1]
        qa = extract_qa_pairs(row["request"]["contents"][0]["parts"][0]["text"].split("<attached image>")[-1].split("**Output format")[0])

        question = qa[0]["caption_pair_1"]['Question']
        answer_1 = qa[0]["caption_pair_1"]['Caption']
        answer_2 = qa[0]["caption_pair_2"]['Caption']

        img_dec = row["response"]["candidates"][0]["content"]["parts"][0]["text"]
        c_img_dec = eval(img_dec.replace("json", "").strip("```"))

        all_res.append([img_name, question, answer_1,  c_img_dec["caption_pair_1"]["hallucination_candidates"], c_img_dec["caption_pair_1"]["hallucinated_words"]])
        all_res.append([img_name, question, answer_2,  c_img_dec["caption_pair_2"]["hallucination_candidates"], c_img_dec["caption_pair_2"]["hallucinated_words"]])
    except Exception as e:
        error += 1

In [110]:
result_df = pd.DataFrame(all_res)

In [112]:
result_df.shape

(27986, 5)

In [111]:
result_df.columns = ["image_path", "question", "answer", "candidates", "hallucination_candidates"]

In [113]:
result_df.to_csv("/Data2/Arun-UAV/NLP/vision_halu/haloc/haloc_extension/caption/gemini_labeled_28k.csv", index=False)

In [114]:
result_df

,image_path,question,answer,candidates,hallucination_candidates
0,2381430.jpg,What do you think is going on in this snapshot?,In this picture we can see one woman is holdin...,"[one, woman, holding, bat, playing, tennis, ba...",[bat]
1,2381430.jpg,What do you think is going on in this snapshot?,In this picture we can see one woman is holdin...,"[one, woman, holding, bat, playing, tennis, fr...","[bat, frisbee]"
2,2378712.jpg,What do you think is going on in this snapshot?,In this picture we can see a bus on road and a...,"[bus, road, footpath, statue, person, building...",[]
3,2378712.jpg,What do you think is going on in this snapshot?,In this picture we can see a bus on road and a...,"[bus, road, footpath, statue, person, building...",[trains]
4,2379616.jpg,Describe the following image.,There is a person standing on a bicycle and th...,"[person, standing, bicycle, car, beside, sitti...","[standing, sitting, bike, left, corner, few, r..."
...,...,...,...,...,...
27981,2398155.jpg,What do you see happening in this image?,"An older woman in a black, white, and gray shi...","[older, woman, black, white, gray, shirt, pant...","[gray, apron, five, stove]"
27982,2347016.jpg,Write a detailed description of the given image.,In this picture we can see a black color cat s...,"[black, cat, sitting, laptop, on, book, pencil...","[cd, remote]"
27983,2347016.jpg,Write a detailed description of the given image.,In this picture we can see a black color cat s...,"[black, cat, sitting, laptop, on, book, pencil...","[left, cd, remote, cup]"
27984,2316274.jpg,Can you elaborate on the elements of the pictu...,In this image there is a dog standing in a roo...,"[dog, standing, room, carpet, books, tables, c...","[standing, toys]"
27985,2316274.jpg,Can you elaborate on the elements of the pictu...,In this image there is a dog standing in a roo...,"[dog, standing, room, carpet, books, tables, c...","[standing, toys, bed, frisbees, scattered]"

In [ ]:
all_res = []
for inx, row in pred_data.iterrows():
    try:
        img_name = row["request"]["contents"][0]["parts"][1]["fileData"]["fileUri"].split("/")[-1]
        img_dec = row["response"]["candidates"][0]["content"]["parts"][0]["text"]
        c_img_dec = eval(img_dec.replace("json", "").strip("```"))["image_description"]
        all_res.append({"image": img_name, "description": c_img_dec})
    except Exception as e:
        print(f"Error processing row {inx}: {e}")

In [39]:
df = pd.DataFrame(all_res)

In [41]:
df.head(2)

,image,description
0,COCO_train2014_000000467172.jpg,The indoor scene captures two domestic cats ex...
1,COCO_train2014_000000328023.jpg,This outdoor scene captures a lively moment in...

In [42]:
old_poc_df  = pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/train_datasets/coco_5000_train_with_gemini_des.csv")

In [92]:
df.to_csv("/Data2/Arun-UAV/NLP/vision_halu/train_datasets/coco_5000_train_with_gemini_des.csv", index=False)

In [43]:
old_poc_df.head(2)

,image,description
0,COCO_train2014_000000078572.jpg,This outdoor scene captures a bustling street ...
1,COCO_train2014_000000401963.jpg,The image captures an outdoor scene under brig...

In [44]:
final_df_15k = pd.concat([old_poc_df, df])

In [46]:
final_df_15k["image"].nunique()

14579

In [47]:
final_df_15k.to_csv("/Data2/Arun-UAV/NLP/vision_halu/train_datasets/coco_batch_1_15000_train_with_gemini_des.csv", index=False)

In [42]:
a = 1

In [119]:
# total_df[total_df["data_type"] != "vqa"]

In [138]:
gen_data = pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/vga_gqa_base_model_res.csv")

In [ ]:
gqa_data = gen_data.head(2)

,question,answer,question_id,image_id,image_path,data_type,generated_captions
0,Are there blankets or curtains?,"Yes, there is a blanket.",f0766969-5b2c-4cb0-9887-a77d33b51a8f,2346216,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,gqa,"Yes, there are blankets and curtains in the im..."
1,Do you see any faucets or coffee pots in the p...,"Yes, there is a coffee pot.",c1c69167-66f9-4463-bcd4-b2391af53dce,2369120,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,gqa,"No, there are no faucets or coffee pots in the..."

In [129]:
# gqa_data = gen_data[gen_data["data_type"] == "gqa"]
# vg_data = gen_data[gen_data["data_type"] == "vga"]

In [139]:
all_datapoints = []
for inx, row in gen_data.iterrows():
    image_path = row["image_path"]
    image_id = row["image_id"]
    data_type = row["data_type"]
    qa_pairs = [{"question": row["question"], "answer": row["answer"]}, {"question": row["question"], "answer": row["generated_captions"]}]
    all_datapoints.append({"image_path": image_path, "image_id": image_id, "data_type": data_type, "qa_pairs": qa_pairs, "question_id": str(inx)})

In [140]:
len(all_datapoints)

27633

In [141]:
total_df = pd.DataFrame(all_datapoints)

In [146]:
total_df.head(2)

,image_path,image_id,data_type,qa_pairs,question_id
0,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,2346216,gqa,[{'question': 'Are there blankets or curtains?...,0
1,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,2369120,gqa,[{'question': 'Do you see any faucets or coffe...,1

In [145]:
total_df.index = range(len(total_df))

In [178]:
total_df = pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/holoc/gemini_labled_total_holoc_data.csv")
# coco_data = pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/coco/gemini_labeld_15k.csv")
# total_df = pd.concat([df, coco_data])
# total_df = total_df[~total_df["data_type"].isin(["instruct", "vqa"])]

In [183]:
total_df["data_type"].value_counts()

data_type
vqa         47588
instruct    22560
caption     17394
Name: count, dtype: int64

In [187]:
total_df[total_df["data_type"] == "vqa"].to_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/holoc/vqa/gemini_labeled_vqa_data_40k.csv", index=False)

In [5]:
total_data = pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/vga_gqa_base_model_res.csv")

In [6]:
total_data.head(2)

,question,answer,question_id,image_id,image_path,data_type,generated_captions
0,Are there blankets or curtains?,"Yes, there is a blanket.",f0766969-5b2c-4cb0-9887-a77d33b51a8f,2346216,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,gqa,"Yes, there are blankets and curtains in the im..."
1,Do you see any faucets or coffee pots in the p...,"Yes, there is a coffee pot.",c1c69167-66f9-4463-bcd4-b2391af53dce,2369120,/Data2/Arun-UAV/NLP/vision_halu/visual_genome/...,gqa,"No, there are no faucets or coffee pots in the..."

In [8]:
import os
import shutil
from pathlib import Path

def copy_target_images(image_paths, destination_folder):
    """
    Copy all target images to a given destination folder.

    Args:
        image_paths (list[str]): List of image file paths (absolute or relative).
        destination_folder (str): Folder where images will be copied.

    Returns:
        list[str]: List of full paths of copied images in the destination.
    """
    dest = Path(destination_folder)
    dest.mkdir(parents=True, exist_ok=True)

    copied_files = []
    for img_path in image_paths:
        src = Path(img_path)
        if src.is_file() and src.suffix.lower() in {'.jpg', '.jpeg', '.png', '.bmp', '.gif', '.tiff', '.webp'}:
            target_path = dest / src.name
            shutil.copy2(src, target_path)
            copied_files.append(str(target_path.resolve()))
        else:
            print(f"⚠️ Skipping invalid or missing image: {img_path}")

    print(f"\n✅ Copied {len(copied_files)} images to: {dest.resolve()}")
    return copied_files

In [ ]:
total_data["imaeg_path"].unique().to_list()

✅ Copied 22898 images to: /Data2/Arun-UAV/NLP/vision_halu/visual_genome/VG_target_20k

In [127]:
gqa_large = pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/gqa/large_gqa_gemini_labeled.csv")
visual_genome_large = pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/vga/large_vga_gemini_labeled.csv")

In [151]:
gqa_small = pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/gqa/small_gqa_gemini_labeled.csv")
visual_genome_small = pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/vga/small_vga_gemini_labeled.csv")

In [152]:
gqa_small.shape

(16440, 8)

In [153]:
gqa_small = gqa_small[gqa_small["answer"].apply(lambda x: x[0].isalpha())]

In [154]:
gqa_small.shape

(16440, 8)

In [155]:
visual_genome_small.to_csv("/Data2/Arun-UAV/NLP/vision_halu/hal_detection_head_train_datasets/gqa/small_gqa_gemini_labeled.csv", index=False)